### ISSUE TITLE
Access to actual dataset used for training

### ISSUE THREAD

**Issue by yellowwoods12** [purvaten/treat#1]
Hi @purvaten, can I somehow get access to the actual letter and clipart dataset used for training this model?

**Comment by purvaten** [comment]
Hi @yellowwoods12 , unfortunately the letter font files that I used are proprietary so I won't be able to share them. You can however download freely available [Google font files](https://fonts.google.com/).

The clipart dataset was obtained by downloading icons from the [Noun Project](https://thenounproject.com/). Owing to legal constraints from Noun Project, I cannot share the icons directly with you. However, Noun Project does provide a nice [API](http://api.thenounproject.com/) which you can play around with to download icons.

As long as you use a large random set of icons (from Noun project and Google fonts), you should still be able to get reasonable results very close to those in the paper even if not exactly the same as our results.

**Comment by yellowwoods12** [comment]
Hi @purvaten, I looked into the API of noun project but I couldn't find a way to download those icons. The API call basically returns a JSON object only. Let me know if you can help here.

**Comment by purvaten** [comment]
@yellowwoods12 the JSON object should contain a `preview_url` field containing the URL - e.g., [https://static.thenounproject.com/png/11742-200.png](https://static.thenounproject.com/png/11742-200.png).

Now to download this, you can simply enter this in yout terminal. 
`wget https://static.thenounproject.com/png/11742-200.png`

The image will be downloaded in the current directory.
